services:
  - type: web
    name: questio-backend
    runtime: docker
    rootDir: questio-backend - Copia
    dockerfilePath: questio-backend - Copia/Dockerfile
    dockerContext: questio-backend - Copia
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: API_SECURITY_TOKEN_EXPIRATION_MS
        value: 7200000
      - key: APP_FRONTEND_URL
        sync: false
      - key: APP_PASSWORD_RESET_URL
        value: questio-app://screens/(Authenticator)/ResetPassWord
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: APP_MAIL_FROM
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: API_SECURITY_TOKEN_SECRET
        generateValue: true
      - key: SPRING_MAIL_HOST
        sync: false
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: SPRING_MAIL_CONNECTION_TIMEOUT
        value: "5000"
      - key: SPRING_MAIL_TIMEOUT
        value: "5000"
      - key: SPRING_MAIL_WRITE_TIMEOUT
        value: "5000"
      - key: QUESTIO_SCHEDULING_RESET_STREAK_ENABLED
        value: "true"
