import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#050E1D",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 8,
  },
  logoContainer: {
    gap: 6,
  },
  headerBadge: {
    alignSelf: "flex-start",
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
    backgroundColor: "rgba(56, 189, 248, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.18)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  headerTitle: {
    color: "#F8FAFC",
    fontSize: 24,
    fontWeight: "800",
  },
  logo: {
    width: 68,
    height: 68,
    borderRadius: 18,
  },
  notification: {
    position: "relative",
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#071427",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.16)",
  },
  notificationBadge: {
    position: "absolute",
    top: -2,
    right: -1,
    backgroundColor: "#ff4757",
    borderRadius: 10,
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#050E1D",
  },
  badgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "bold",
  },

  content: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 120,
  },
  brandCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    backgroundColor: "#071427",
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.18)",
    shadowColor: "#020617",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.24,
    shadowRadius: 24,
    elevation: 10,
  },
  brandTextContainer: {
    flex: 1,
    gap: 6,
  },
  brandEyebrow: {
    color: "#38BDF8",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  brandText: {
    color: "#E2E8F0",
    fontSize: 15,
    lineHeight: 22,
  },
  section: {
    marginTop: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  verTodas: {
    color: "#38BDF8",
    fontSize: 13,
    fontWeight: "600",
  },
  progressBarTrack: {
    height: 14,
    backgroundColor: "#0F2137",
    borderRadius: 99,
    overflow: "hidden",
    marginTop: 8,
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#38BDF8",
    borderRadius: 99,
    minWidth: 8,
  },
  progressLabel: {
    color: "#94A3B8",
    fontSize: 12,
    marginTop: 8,
  },
 card: {
    backgroundColor: "#071427",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 20,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.18)",
  },
  tarefaCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#071427",
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.12)",
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "#38BDF8",
    marginRight: 12,
    flexShrink: 0,
    marginTop: 2,
  },
  tarefaContent: {
    flex: 1,
  },
  tarefaTitulo: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 6,
    lineHeight: 19,
  },
  tarefaMeta: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  categoriaBadge: {
    backgroundColor: "rgba(34,197,94,0.14)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  categoriaText: {
    color: "#4ADE80",
    fontSize: 11,
    fontWeight: "600",
  },
  atrasadaText: {
    color: "#F59E0B",
    fontSize: 11,
    fontWeight: "500",
  },
  pontos: {
    color: "#F8FAFC",
    fontSize: 13,
    fontWeight: "700",
    marginLeft: 8,
    marginTop: 2,
  },
  emptyText: {
    color: "#94A3B8",
    fontSize: 14,
    textAlign: "center",
    marginTop: 12,
  },
  atalhoCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#0A1929",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  atalhoText: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
});
