spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/questio_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

api.security.token.secret=${API_SECURITY_TOKEN_SECRET:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
